export default {
  totalComplaint: "कुल गुनासो",
  complaintsQueue: "कतारमा रहेका गुनासोहरू",
  complaintsProgress: "प्रगतिमा रहेका गुनासोहरू",
  completed: "सम्पन्न",
  registerComplaint: "गुनासो दर्ता गर्नुहोस्",
  complaintTitle: "गुनासोको शीर्षक",
  description: "विवरण",
  complaintCategory: "गुनासो श्रेणी",
  uploadImages: "तस्वीरहरू अपलोड गर्नुहोस्",
  submit: "पेश गर्नुहोस्",
  latestComplaints: "नवीनतम गुनासोहरू",
  no: "अङ्क",
  status: "स्थिति",
  date: "मिति",
  complaints: "गुनासोहरू",
  logout: "लगआउट",
  public: "सार्वजनिक",
  private: "निजी",
  all: "सबै",
  success: "सफलता",
  progress: "प्रगति",
  queue: "कतार",
  profile: "प्रोफाइल",
  name: "नाम",
  email: "ईमेल",
  phoneNumber: "फोन नम्बर",
  address: "ठेगाना",
  NoComplaints:"कुनै प्रतिवेदन छैन",
  FilterBy:"फिल्टर गर्नुहोस्",
  yourComplaints: "तपाईंको उजुरीहरू",
  wantLogout: "तपाईंले लगअउट गर्न चाहानुहुन्छ?",
  wantLogin: "तपाईंले लगिन गर्न चाहानुहुन्छ?",
  yes:"हो",
  no:"होइन",
  complainRegistered:"तपाईंको गुनासो दर्ता गरिएको छ",
  provideEmail: "ईमेल दिनुहोस्",
  providePassword: "पासवर्ड दिनुहोस्",
  loginText: "अहिले लगइन गर्नुहोस् र सबै सुविधाहरूमा पहुँच प्राप्त गर्नुहोस्",
  singintext: "हरेक सुविधाको पहुँचको लागि अब साइन इन गर्नुहोस्",
  noAccount: "खाता छैन? ",
  signup: "साइन अप गर्नुहोस्",
  forgot: "पासवर्ड बिर्सनुभयो?",
  login: "लगइन गर्नुहोस्",
  fullname: "पुरा नाम",
  number: "फोन नम्बर",
  email: "ईमेल ठेगाना",
  password: "पासवर्ड",
  address:"ठेगाना",
  cpassword:"पासवर्ड सुनिश्चित गर्नुहोस्",
  choose: "विकल्प छनौट गर्नुहोस्",
  chooseArea: "क्षेत्र छनौट गर्नुहोस्"

  

}