export default {
    totalComplaint: "Total",
    complaintsQueue: "In Queue",
    complaintsProgress: "On Progress",
    completed: "Completed",
    registerComplaint: "Register Complaint",
    complaintTitle: "Complaint Title",
    description: "Description",
    complaintCategory: "Complaint Category",
    uploadImages: "Upload Images",
    submit: "Submit",
    latestComplaints: "Latest Complaints",
    no: "No",
    status: "Status",
    date: "Date",
    complaints: "Complaints",
    logout: "Logout",
    public: "public",
    private: "private",
    all: "All",
    success: "Success",
    progress: "Progress",
    queue: "Queue",
    profile: "Profile",
    name: "Name",
    email: "E-mail",
    phoneNumber: "Phone Number",
    address: "Address",
    NoComplaints: "No Complaints at the moment.",
    FilterBy: "Filter By",
    yourComplaints: "Your Complaints",
    wantLogout: "Do you want to logout?",
    wantLogin: "Do you want to login?",
    yes: "Yes",
    no: "No",
    complainRegistered: "Your complaint has been registered",
    provideEmail: "Enter your email",
    providePassword: "Enter password",
    loginText: "Login now to access the whole feature",
    singintext: "Sign up now to access the whole feature",
    noAccount: "Don't have an account? ",
    signup: "Signup",
    forgot: "Forgot Password?",
    login: "Login",
    fullname: "Full Name*",
    number: "Phone Number",
    email: "Email Address*",
    password: "Password*",
    address: "Address",
    cpassword:"Comfirm Password*",
    choose: "Choose an option",
    chooseArea: "Choose Area"



}



// const translations = {
//     en: {
//       dashboard: "Dashboard",
//       totalComplaint: "Total Complaints",
//       complaintsQueue: "Complaints in Queue",
//       complaintsProgress: "Complaints in Progress",
//       completed: "Completed",
//       registerComplaint: "Register Complaint",
//       complaintTitle: "Complaint Title",
//       description: "Description",
//       complaintCategory: "Complaint Category",
//       uploadImages: "Upload Images",
//       submit: "Submit",
//       latestComplaints: "Latest Complaints",
//       no: "No",
//       status: "Status",
//       date: "Date",
//       complaints: "Complaints",
//       logout: "Logout",
//       public: "Public",
//       private: "Private",
//       viewAll: "View All",
//       allComplaints: "All Complaints",
//       all: "All",
//       success: "Success",
//       progress: "Progress",
//       queue: "Queue",
//       profile: "Profile",
//       name: "Name",
//       email: "E-mail",
//       phoneNumber: "Phone Number",
//       address: "Address",
//       userComplaints: "User's Complaints",
//     },
//     ne: {
//       dashboard: "ड्यासबोर्ड",
//       totalComplaint: "कुल गुनासो",
//       complaintsQueue: "कतारमा रहेका गुनासोहरू",
//       complaintsProgress: "प्रगतिमा रहेका गुनासोहरू",
//       completed: "सम्पन्न",
//       registerComplaint: "गुनासो दर्ता गर्नुहोस्",
//       complaintTitle: "गुनासोको शीर्षक",
//       description: "विवरण",
//       complaintCategory: "गुनासो श्रेणी",
//       uploadImages: "तस्वीरहरू अपलोड गर्नुहोस्",
//       submit: "पेश गर्नुहोस्",
//       latestComplaints: "नवीनतम गुनासोहरू",
//       no: "अङ्क",
//       status: "स्थिति",
//       date: "मिति",
//       complaints: "गुनासोहरू",
//       logout: "लगआउट",
//       public: "सार्वजनिक",
//       private: "निजी",
//       viewAll: "सबै हेर्नुहोस्",
//       allComplaints: "सबै गुनासोहरू",
//       all: "सबै",
//       success: "सफलता",
//       progress: "प्रगति",
//       queue: "कतार",
//       profile: "प्रोफाइल",
//       name: "नाम",
//       email: "ईमेल",
//       phoneNumber: "फोन नम्बर",
//       address: "ठेगाना",
//       userComplaints: "प्रयोगकर्ताको गुनासोहरू",
//     },
//   };